[STEP 1] volga, summer
2023newkrew/ios-grade-manager pull request #1
Opened 2022-12-27 08:17 UTC by shinhee-rebecca

- [ ] 메뉴 출력 및 메뉴의 잘못된 입력 처리
- [ ]

2022-12-28 01:25 UTC, wonhee009 requested changes
수고하셨습니다.
코멘트 남겨두었으니 확인 부탁드립니다.
(이후 PR에서는 어떤 부분을 고민했는지 PR 내용에 추가 부탁드립니다.)

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +struct GradeManager {
struct로 정의한 이유가 있을까요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +    case null
사용자가 아무것도 입력하지 않았을때 에러인거로 보이는데요.
`null`이라고 케이스 네이밍한 이유가 있을까요?
swift에서는 `null`이 아닌 `nil`을 사용하기도 하고, `InputError.null`은 에러가 비었다는건지 빈 입력에 대한 에러인지 알기 어려울거 같습니다.
`null`보다는 `empty`같은 네이밍은 어떤가요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +    case null
또한 `wrong`이라는 네이밍보다는 구체적인 네이밍은 어떤가요?
해당 에러가 발생하는 상황을 보니 없는 메뉴에 대한 input이 들어왔을때 발생하는거 같은데요.
이런 상황이 잘 들어나는 네이밍이면 좋을거 같습니다.

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +        case "1", "2", "3", "4", "5", "X":
"1", "2", .... 가 메뉴 문자열로 보입니다.
enum을 이용해 메뉴를 정의하고 enum을 활용해보는건 어떤가요?
``` swift
enum Menu: String {
   case .studentAdd = "1"
   ...
}

guard let choiceMenu = Menu(rawValue: choice) else {
   return .failure(.wrong)
}
...
```

이런식으로 enum과 rawValue를 이용한다면 문자열을 주고받지 않고 enum Type으로 주고 받을 수 있을거 같습니다.

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +        case deleteFailure = " 학생을 찾지 못했습니다."
프로그램에서 사용하는 문자열 상수를 정의한거로 이해했습니다.
rawValue를 사용한 이유가 있을까요?
``` swift
enum InfoMessage {
   static let addSuccess = "학생을 추가했습니다."
   ...
}
```
이런 식으로 타입 프로퍼티를 이용할 수 있습니다.
`InfoMessage`가 `DefaultStudentManager` 내에서만 사용되는거 같은데요.
private으로 제한할 필요는 없을까요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +struct DefaultStudentManager: StudentManager {
`Default`는 어떤 의미로 붙은건가요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +        return false
[Set](https://developer.apple.com/documentation/swift/set)의 `contains` 메서드를 활용할 수 있지 않을까요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +        }
early exit 상황으로 보이는데요. [guard문](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html) 활용해보는건 어떤가요?

2022-12-28 01:25 UTC, wonhee009 commented on GradeManager/main.swift
> +        while true {
while true보다는 프로퍼티를 통해 제어하는건 어떨까요?
``` swift
let canExit: Bool

while canExit { ... }
```
이런 식으로요. 현재는 어떤 상황에서 탈출하는지 로직을 보지 않고는 알기 힘든거 같습니다.

2022-12-28 01:25 UTC, wonhee009 commented on UnitTestGradeManager/UnitTestGradeManager.swift
> +    }
정의한 errorType (null, wrong)에 대해 케이스를 나눠서 테스트 코드를 추가해주세요.

2022-12-28 01:25 UTC, wonhee009 commented on UnitTestGradeManager/UnitTestGradeManager.swift
> +    }
사용하지 않는 코드라면 삭제 부탁드립니다.

2022-12-28 01:25 UTC, wonhee009 commented on UnitTestGradeManager/UnitTestGradeManager.swift
> +class UnitTestGradeManager: XCTestCase {
addStudent, deleteStudent에 대한 테스트 코드는 필요 없나요?

2022-12-28 14:57 UTC, volgaHwang commented on GradeManager/main.swift
> +struct GradeManager {
안녕하세요 라자냐

Struct를 사용한 이유는 다음과 같습니다.
일단, Class를 사용할지 Struct를 사용할지 Summer랑 페어프로그래밍 전에 논의를했는데요,

1. Apple Developer Academy에서 제시하는 Struct / Class를 사용하는 가이드 라인을 볼 경우
- Use structures by default.
- Use classes when you need Objective-C interoperability.
- Use classes when you need to control the identity of the data you’re modeling.
- Use structures along with protocols to adopt behavior by sharing implementations.

위의 글에서 제시된 것 처럼, 해당 집합체가 Objective-C와 interoperability가 필요없는 상태고
딱히 동일성(Identity)에 대해 신경을 쓸 이유가 없다고 생각했기 때문입니다.
단순하게 GradeManager로서 동작확인이 목적이라면 Default로 제시되어있는 Struct를 쓰는 것이 좋겠다고 판단했습니다.

2. 두번째 이유로는 굳이 가이드라인에서 제시하는 위의 네 문장을 제외하더라도 주소값을 통해 어떤 무언가를 해야 할 경우에 사용하게 될텐데, 해당 과제에서는 Reference Type을 사용할 이유가 없다고 판단했기 때문입니다.

2022-12-28 15:00 UTC, volgaHwang commented on GradeManager/main.swift
> +    case null
null이라고 네이밍을 지은 이유는 비어있는 상태를 어떻게 표현하면 좋을지 생각하다가 null이 적당하겠구나! 하는 생각에 지었습니다.
말씀 주신대로 ```null```보다는 ```empty```가 좋을것 같고 정확하게 어떠한것이 ```empty```한것인지에 대해 명시적으로 알려줄수 있는 것이 있는지 리팩토링 해야할것같습니다.

2022-12-28 15:07 UTC, volgaHwang commented on GradeManager/main.swift
> +        case deleteFailure = " 학생을 찾지 못했습니다."
- 프로그램에서 사용하는 문자열 상수를 정의한거로 이해했습니다.
rawValue를 사용한 이유가 있을까요?
    - rawValue를 통해 InfoMessage 의 printing을 사용하면, ```InfoMessage.add.printing()```같이 출력하는 방식을 선택했기 때문입니다.
- ```InfoMessage```가 ```DefaultStudentManager``` 내에서만 사용되는거 같은데요. private으로 제한할 필요는 없을까요?
    - 말씀 주신대로, 불필요하게 외부에 노출이 될 필요가 없는 것 같습니다.

2022-12-28 15:08 UTC, volgaHwang commented on GradeManager/main.swift
> +        while true {
오.. 이 부분은 처음에 굉장히 고민을 많이했던 부분인데 한번 참조에서 리팩토링 진행해보겠습니다 :)

2022-12-29 06:09 UTC, wonhee009 commented on GradeManager/main.swift
> +        case deleteFailure = " 학생을 찾지 못했습니다."
`InfoMessage.add.printing()`과 같은 방식을 사용하려 해당 rawValue로 구현한거로 이해했습니다.
`print(InfoMessage.add.rawValue)`가 위의 코드와 동일하게 동작할거 같은데요.
다른 사람이 봤을때에는 `.printing()`, `print()` 어떤걸 써야할지 혼란스러울거 같기도 하고, 누군가 `printing` 메서드의 존재를 알려주지 않으면 혼용되서 사용할 가능성이 높아보입니다.
보통 이런 문자열 상수는 `static let`처럼 타입 프로퍼티를 이용해서 정의하는데요. 이런 방식은 어떨까요?

2022-12-30 08:38 UTC, wonhee009 requested changes
수고하셨습니다.
코멘트 남겨두었으니 확인 부탁 드립니다.

- Student를 구조체로 유지하고 싶으신 이유가 따로 있으신걸까요? mutating을 이용해 내부를 변경할 수는 있습니다만, 구조체와 클래스의 차이점에 대해 좀 더 생각해보면 좋을거 같습니다. 이전 코멘트에서 적어주셔듯이 어떤 경우에 구조체/클래스를 사용하도록 권장하는지에 대해 생각해보면 좋을거 같습니다. (저는 구조체가 immutable한 속성을 갖고 있는만큼 mutating한 행위를 할 필요가 있다면 class로 정의하는게 맞다고 생각합니다.)

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/Student.swift
> +    private var courseManager: CourseManager
Student가 courseManager를 갖고 있는 부분이 조금 부자연스러운거 같은데요.
`CourseManager`가 InfoMessage나 Grade에 대해 가지고 있는거로 보입니다.
Student가 courseManger를 갖으면서 모든 student 객체는 infoMesage, Grade enum에 대한 타입을 갖고 있게 될거 같습니다.
이런 타입이 모든 student 객체가 갖는게 의도하신 방향일까요?

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/InputManager.swift
> +    }
메서드명은 평점을 보여줘야할거 같은데 학생 이름을 반환하고 있는거 같습니다.
메서드명과 역할이 동일하도록 해주세요.

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/InputManager.swift
> +    func addStudentGradeInfo() -> Result<(name: String, subject: String, grade: String), InputError> {
이후에 info에 학생 전화번호가 추가되면 `(name: _, subject: _, grade: _, phoneNumber: _)` 이런식으로 무한히 확장되는 걸까요?
`Student`나 `GradeInfo` 같이 모델을 추가하는건 어떤가요?

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/StudentManager.swift
> +struct DefaultStudentManager: StudentManager {
이전 코멘트에도 남겼지만 Default는 어떤 의미인가요? 다른 StudentManger가 있는걸까요?
(https://github.com/2023newkrew/ios-grade-manager/pull/1#discussion_r1058001361)

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/StudentManager.swift
> +        return list.contains(Student(name: name))
입력받은 name으로 Student 객체를 만들고 새로 만든 객체를 통해 contains 여부를 확인하는거로 이해했습니다.
name이 동일하다면 true를 반환하는거로 이해했습니다. Student 객체를 만들지 않고 확인할 수 없을까요?
contains를 수행하기 위해 새로운 객체를 만드는게 어색한거 같습니다.

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/StudentManager.swift
> +    func studentToBeDeleted(name: String) -> Student? {
`deleteStudent()`에서 받은 이름이 삭제 가능한 학생의 이름인지 확인하는 메서드로 이해했습니다.
`willDeleteStudent`정도의 네이밍은 어떤가요?

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/StudentManager.swift
> +        return list.contains(Student(name: name))
이 메서드는 StudentManager 내부에서만 사용하나요? 그렇다면 private으로 외부 접근을 막을 필요는 없을까요?

2022-12-30 08:38 UTC, wonhee009 commented on GradeManager/StudentManager.swift
> +    func studentToBeDeleted(name: String) -> Student? {
또한 해당 메서드 StudentManager 내에서만 사용될거 같은데요. private으로 외부 접근을 막을 필요는 없을까요?

2022-12-31 15:14 UTC, volgaHwang commented on GradeManager/main.swift
> +        case deleteFailure = " 학생을 찾지 못했습니다."
안녕하세요. 라자냐.

제가 지난 금요일에 다른 공적으로 처리해야할 문서들 때문에 참여를 못해서 늦게나마 답변을 답니다.
리뷰에 대한 이해를 제대로 하고있는게 맞는지 살짝은 저도 혼동이 되는데요 ㅎㅎㅎ

굳이 ```InfoMessage```라는 Enumerate에 String으로 ```rawValue```를 사용하는 것보다는
케이스에 맞게 ```static```을 이용한 상수로 출력을 해주는 방식을 이용하는 것을 추천하신다고 이해를 했습니다.

만약 제가 이해한 부분이 맞다면, 저도 이 부분에 대해서 동의합니다.
이유는 두 가지인데요, case에서 한번 더 해당 부분에 대한 ```rawValue```를 찾는 것이 조금은 비효율적인 코드로 보이고,
실제로 코드를 작성하는 경우에 있어서도 ```rawValue``` 키워드를 그대로 사용하는 것은 가독성이 좋지 않다고 판단이 들기 때문입니다.

그리고 말씀 주신 printing(), print() 키워드에 대해서도 헷갈리는 지점이 있다는 것에 동의합니다.
이 부분도 썸머와 함께 논의 해서 수정을 진행해보고 다시 PR을 올려보겠습니다 :)

2022-12-31 15:18 UTC, volgaHwang commented on UnitTestGradeManager/UnitTestGradeManager.swift
> +class UnitTestGradeManager: XCTestCase {
테스트 코드는 필요하다고 생각합니다.

[f994026](https://github.com/2023newkrew/ios-grade-manager/pull/1/commits/f994026d2c31bc4f14d3d88397381a0077e9417d) 말씀 하신 테스트에 대한 패치를 전달드립니다!

2023-01-04 09:09 UTC, shinhee-rebecca commented on GradeManager/StudentManager.swift
> +    func studentToBeDeleted(name: String) -> Student? {
위 메서드는 삭제할 학생을 찾아서 반환하는 메서드입니다. (학생을 찾지 못하면 nil을 반환하게 됩니다.) 해당 메서드를 private으로 막는것이 더 적절할 것 같습니다.

2023-01-04 09:11 UTC, shinhee-rebecca commented on GradeManager/StudentManager.swift
> +        return list.contains(Student(name: name))
Student 객체를 만들지 않고도 확인할 수 있을 것 같습니다. contains를 수행하기 위해 객체를 만드는건 저도 어색하게 보입니다. private 접근 지정을 하는 것이 좋은 것 같습니다.

2023-01-04 09:12 UTC, shinhee-rebecca commented on GradeManager/StudentManager.swift
> +struct DefaultStudentManager: StudentManager {
StudentManger 라는 이름의 protocol이 존재하여 struct의 이름에 Default를 붙였습니다. struct에 default를 붙이는 것 말고 protocol과 struct의 네이밍 방식에는 어떤 것이 있을까요?

2023-01-04 09:15 UTC, shinhee-rebecca commented on GradeManager/InputManager.swift
> +    func addStudentGradeInfo() -> Result<(name: String, subject: String, grade: String), InputError> {
확장성을 고려했을 때 name: String, subject: String, grade: String 보다는 student: Student를 Result에 포함하는 것이 적절해보입니다. 감사합니다!

2023-06-12 23:18 UTC, closed without merging