성적관리 [STEP 1] Forest, John
2023newkrew/ios-grade-manager pull request #2
Opened 2022-12-28 01:09 UTC by forestjae

@zdodev 
안녕하세요 소대! 포레스트와 존 입니다. 잘부탁드려요🙇🏻‍♂️🙇🏻‍♂️

## 고민한점
### 1. TDD를 진행하고, 테스트 커버리지를 신경 썼습니다.
테스트 케이스를 먼저 만들고, 코드를 작성하는 방법을 통해 진행하였습니다. 콘솔 입/출력부분을 제외하고 모두 테스트를 진행했습니다.

### 2. 에러 처리에 대한 고민을 했습니다.
중복된 학생이 있어 추가가 안되는 경우, 삭제할 학생이 없는 경우 등 이러한 상황에서 에러를 던져야 하는지에 대한 고민을 했습니다. 에러 처리를 하지 않고 true/false로 분기를 나눠 작업을 처리했습니다. 

## 질문
TDD를 할때 어느정도 설계를 하고 테스트코드 작성으로 넘어가야 하는지, 아니면 아무 설계도 하지 않고 테스트 부터 작성하는게 맞는지 궁금합니다!

2022-12-28 09:35 UTC, zdodev requested changes
안녕하세요. 포레스트, 존!
리뷰를 진행하게 된 소대입니다!

파일 분할을 적절하게 해주신 점과 테스트 코드까지 작성해주신 부분이 좋았습니다!👍

다만 프로젝트 기능 명세 일부분이 구현되지 않아보입니다. 명세에 따라 해당 기능도 구현이 되야 될 것 같습니다!
- 초기 메뉴에 없는 값을 입력하면 프로그램이 종료되고 있는데, 잘못된 입력 처리를 해볼 수 있을까요?
- 학생 추가 시, 잘못 입력한 것에 대한 처리를 추가해 볼 수 있을까요?
- 학생 삭제 시, 삭제한 학생의 이름이 출력되지 않는 부분을 수정할 수 있을까요?

이 외에 궁금한 사항은 코멘트로 남겨보았습니다! 

그리고 질문에 대한 제 생각은 TDD 라는 방법론을 적용할 때, 처음부터 무작정 테스트를 작성하려고 한다면 어렵고 힘들 수 있습니다. 그래서 필요에 따라 어느정도 설계를 하는 것이 더 좋은 방향이라고 생각합니다.
테스트 작성이 익숙해지고 숙련될 때까지 꾸준히 연습을 해보는 것이 좋을 것 같습니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/main.swift
> +GradeManager().run()
`main` 에 프로그램 실행 구문만 작성해보셨네요.👍

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +class GradeManager {
`GradeManager` 타입을 클래스로 선언하신 이유가 궁금합니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +    var students: [String: Student] = [:]
외부에서 사용하지 않는다면 접근제어 수준을 바꿔보는 것은 어떨까요?

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +    }
외부에서 사용하지 않는다면 접근제어 수준을 바꿔보는 것은 어떨까요?
다른 메서드도 확인해보면 좋겠습니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +    menuLoop: while let input = receiveInput(message: .selectMenu) {
반복문 탈출조건으로 statement label 문법을 사용하신 이유가 궁금합니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +        self.students[name] = student
`self` 키워드를 사용할 때와 사용하지 않을 때의 기준이 궁금합니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +        guard isExisting(name: name) else {
학생의 유무를 판단하는 의미는 `addStudent` 메서드의 `if`문과 동일해보입니다.
여기에서는 다른 형태(`guard` 문)로 구현하신 이유가 궁금합니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/GradeManager.swift
> +        guard let _ = self.students[name] else {
추가된 학생의 유무를 판단할 때, `if` 문이 아닌 `guard let` 구문을 사용하신 이유가 궁금합니다!

2022-12-28 09:35 UTC, zdodev commented on GradeManager/MessageTemplate.swift
> +enum MessageTemplate: CustomStringConvertible {
문자열을 모아서 관리해두셨네요. 좋습니다!👍

2022-12-28 09:35 UTC, zdodev commented on GradeManager/Student.swift
> +struct Student {
학생을 구조체로 표현해보셨네요. 좋습니다.👍

2022-12-29 00:46 UTC, limjae commented on GradeManager/GradeManager.swift
> +class GradeManager {
GradeManager의 경우 요구사항에  View를 다루는 사항은 없지만
만약 여러 ViewController에서 한 GradeManager에 접근한다고 가정 했을 때
identity를 가지는 장점이 있는 class로 선언하는 것이 유리하다고 판단했습니다.

2022-12-29 00:52 UTC, forestjae commented on GradeManager/GradeManager.swift
> +    menuLoop: while let input = receiveInput(message: .selectMenu) {
return을 사용해도 되지만, menu Loop 이후에 추가적인 로직이 있을 경우 그 로직이 실행되지 않고 종료되기 때문에 향후에 설계변경을 대비하여 이렇게 작성했습니다. 혹시 다른 추천해주실 방법이 있으신가요?

2022-12-29 00:58 UTC, forestjae commented on GradeManager/GradeManager.swift
> +        guard isExisting(name: name) else {
!(expression)의 경우 가독성을 해치는것 같아 !를 사용하지 않고 작성하였습니다. 다만 말씀해주신대로 유사한 로직을 if와 guard문으로 혼동을 주는것 역시 가독성이 좋지 않은 것 같아 수정하겠습니다!

2022-12-29 01:06 UTC, forestjae commented on GradeManager/GradeManager.swift
> +        guard let _ = self.students[name] else {
if문을 사용하면 if ~ == nil 과 같은 형태로 nil과 비교연산을 하는게 싫어서 이렇게 작성했는데, 명확한 근거는 없었습니다. 이렇게 작성하면 Student 타입이 이 메서드 내부에서 필요할때 쓸 수 있는 장점이 있는 것 같은데, 소대는 어떻게 생각하시나요?

2022-12-29 01:53 UTC, forestjae commented on GradeManager/GradeManager.swift
> +    var students: [String: Student] = [:]
해당 프로퍼티의 접근제어자를 private(set)으로 변경했습니다. 다른 요소들도 필요 시 반영 완료했습니다!

2022-12-29 01:55 UTC, forestjae commented on GradeManager/GradeManager.swift
> +        self.students[name] = student
예외없이 전부 붙이려고 했는데 누락됐네요 :( 
수정했습니다!!!

2022-12-30 01:15 UTC, zdodev commented on GradeManager/GradeManager.swift
> +    menuLoop: while let input = receiveInput(message: .selectMenu) {
`if` 나 `while` 의 조건문을 사용할 수도 있지만 statement label 을 사용하신 이유가 궁금했습니다. 지금과 같은 의견도 좋습니다.👍

2022-12-30 01:49 UTC, zdodev commented on GradeManager/GradeManager.swift
> +        guard let _ = self.students[name] else {
`isExisting` 메서드의 역할은 등록된 학생의 존재 여부라고 생각이 들었습니다. 그래서 지금처럼 학생의 유무만 판단하도록 작성했을 것 같습니다. 이후 `Student` 타입이 필요해진다면 `Student` 을 사용하는 메서드를 추가로 구현하지 않을까 싶습니다.
개인적으로 리턴 값을 무의미하게 사용하지 않으려고 와일드카드 패턴을 최대한 지양하고 있습니다.😅 지금도 좋습니다!👍

다음과 같은 방법도 괜찮을 것 같습니다! 의견이 궁금합니다!

```swift
return students[name] != nil
```

2022-12-30 01:52 UTC, zdodev approved these changes
안녕하세요. @forestjae , @limjae !

step1의 기능 구현과 적절한 피드백 수정 잘해주셨습니다!
그리고 궁금증에 대하여 자신만의 생각을 잘 얘기해주신 점이 좋았습니다.👍👍

코멘트에 대하여 의견 남겨보았습니다. 확인 부탁드립니다!

step 1 진행하시느라 고생하셨습니다!

2022-12-30 01:53 UTC, merged

2022-12-30 03:29 UTC, limjae commented on GradeManager/GradeManager.swift
> +        guard let _ = self.students[name] else {
제안해주신 방법이 더 간결하게 표현된다고 판단하여 제안해주신 방법으로 반영하겠습니다!